### ISSUE TITLE
getText() returns text twice

### ISSUE THREAD

**Issue by clemi1995** [ahmadaghazadeh/CodeEditor#3]
Hello,

i have a problem with the following code snipped:

`codeEditor = findViewById(R.id.codeeditor);`
`codeEditor.setText("TEST", 1);`
`codeEditor.getText();  // method getText() returns "TESTTEST"`

The text which gets returned is doubled.
Am i doing something wrong or is this a bug?

Regards

**Comment by ahmadaghazadeh** [comment]
The bug is fixed.
